In [1]:
import pandas as pd
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
import numpy as np
import statsmodels.api as sm
import sklearn.metrics as metrics

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
ml = pd.read_pickle("model_base_v0.pkl")
ml

date  shots  powerPlayTimeOnIce  penaltyMinutes  shifts  \
2005020004   7323      5               378.0               2      21   
2005020020   7325      1               434.0               0      22   
2005020029   7326      3               450.0               4      21   
2005020042   7328      6               272.0               2      18   
2005020054   7330      6               272.0               0      17   
...           ...    ...                 ...             ...     ...   
2022020566  13617      6                98.0               0      24   
2022020580  13619      5               355.0               2      23   
2022020599  13622      7               120.0               0      25   
2022020617  13624      2                95.0               0      20   
2022020622  13625      4               353.0               0      19   

            timeOnIce  isHome  isOT  Anaheim Ducks  Arizona Coyotes  ...  \
2005020004     1056.0       1     0              0                0  ...   
2005020020     1064.0       1     0              0                0  ...   
2005020029      981.0       0     0              0                0  ...   
2005020042      903.0       1     0              0                0  ...   
2005020054      833.0       0     0              0                0  ...   
...               ...     ...   ...            ...              ...  ...   
2022020566     1277.0       1     1              0                0  ...   
2022020580     1171.0       1     0              0                0  ...   
2022020599     1233.0       1     1              0                0  ...   
2022020617     1088.0       0     0              0                0  ...   
2022020622     1349.0       1     0              0                0  ...   

            Pittsburgh Penguins  San Jose Sharks  Seattle Kraken  \
2005020004                    0                0               0   
2005020020                    0                0               0   
2005020029                    0                0               0   
2005020042                    0                0               0   
2005020054                    0                0               0   
...                         ...              ...             ...   
2022020566                    0                0               0   
2022020580                    0                0               0   
2022020599                    0                0               0   
2022020617                    0                0               0   
2022020622                    0                0               0   

            St. Louis Blues  Tampa Bay Lightning  Toronto Maple Leafs  \
2005020004                0                    0                    0   
2005020020                0                    0                    0   
2005020029                0                    0                    0   
2005020042                0                    0                    0   
2005020054                0                    0                    0   
...                     ...                  ...                  ...   
2022020566                0                    0                    0   
2022020580                0                    0                    0   
2022020599                0                    0                    0   
2022020617                0                    0                    0   
2022020622                0                    0                    0   

            Vancouver Canucks  Vegas Golden Knights  Winnipeg Jets  goals  
2005020004                  0                     0              0      2  
2005020020                  0                     0              0      0  
2005020029                  0                     0              0      0  
2005020042                  0                     0              0      1  
2005020054                  0                     0              0      1  
...                       ...                   ...            ...    ...  
202202056

In [14]:
ml.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1316 entries, 2005020004 to 2022020622
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   date                   1316 non-null   int64  
 1   shots                  1316 non-null   int32  
 2   powerPlayTimeOnIce     1316 non-null   float64
 3   penaltyMinutes         1316 non-null   int32  
 4   shifts                 1316 non-null   int32  
 5   timeOnIce              1316 non-null   float64
 6   isHome                 1316 non-null   int32  
 7   isOT                   1316 non-null   int32  
 8   Anaheim Ducks          1316 non-null   uint8  
 9   Arizona Coyotes        1316 non-null   uint8  
 10  Atlanta Thrashers      1316 non-null   uint8  
 11  Boston Bruins          1316 non-null   uint8  
 12  Buffalo Sabres         1316 non-null   uint8  
 13  Calgary Flames         1316 non-null   uint8  
 14  Carolina Hurricanes    1316 non-null   ui

In [8]:
ml.corr()['goals'].sort_values()

timeOnIce               -0.080047
isOT                    -0.064275
Boston Bruins           -0.049421
Colorado Avalanche      -0.031063
penaltyMinutes          -0.030865
Dallas Stars            -0.027589
Los Angeles Kings       -0.027589
Pittsburgh Penguins     -0.026433
Phoenix Coyotes         -0.024266
Carolina Hurricanes     -0.023350
New Jersey Devils       -0.022051
Columbus Blue Jackets   -0.021368
powerPlayTimeOnIce      -0.021164
Arizona Coyotes         -0.020578
Anaheim Ducks           -0.011692
date                    -0.010610
isHome                  -0.007191
Vegas Golden Knights    -0.006356
Vancouver Canucks       -0.005540
San Jose Sharks         -0.005540
New York Rangers        -0.001841
Florida Panthers         0.002572
Chicago Blackhawks       0.003649
Edmonton Oilers          0.003649
Nashville Predators      0.004549
Calgary Flames           0.006461
Seattle Kraken           0.009666
Buffalo Sabres           0.009974
Tampa Bay Lightning      0.011166
New York Islan

In [75]:
X = ml.drop('goals', axis=1)
y = ml.goals

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [22]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.coef_, lr.intercept_

(array([-4.23071827e-06,  1.11913742e-01,  8.81665517e-05, -2.00422270e-02,
         2.72004917e-02, -1.04869487e-03,  3.59434772e-02, -1.35947474e-01,
         1.43227529e-02, -7.99501179e-02,  2.08853881e-02, -1.11873308e-01,
        -3.81813731e-02, -1.56231052e-01, -1.02626651e-01,  1.25013151e-02,
        -1.98646897e-01, -1.16631129e-01, -5.85843961e-02, -1.42236192e-03,
         6.37195497e-02, -6.08043755e-03, -1.21268865e-01,  2.37802853e-01,
         2.08694063e-02,  6.01480972e-02,  2.07367027e-02,  2.16710595e-02,
        -2.73233173e-02,  8.92453187e-02,  1.23045973e-01, -4.25376454e-01,
        -4.75239709e-02,  2.17306352e-02,  8.84612670e-03,  3.44004787e-01,
        -1.96586448e-02,  1.72298015e-01, -6.78449834e-03,  1.32849163e-01,
         1.53486332e-01]),
 0.8213069035582248)

In [23]:
lr.predict(X_test)

array([ 0.00264602,  0.44960435,  0.03769969,  0.79338206,  0.61716492,
        0.65513657,  0.28196355,  0.59899912,  0.45173111,  0.19807058,
        0.65938394,  0.62834845,  0.53475565,  0.6110553 ,  0.46685499,
        0.30220017,  0.81663518,  1.03534029,  0.46506479,  0.73024811,
        1.17759152,  0.42901204,  0.64588706,  0.58927504,  0.79253141,
        0.66790274,  0.18781904,  0.21707984,  0.80355474,  0.29607617,
       -0.0741968 ,  0.41989095,  1.29206188,  0.10624023,  1.17387211,
        0.18742363,  0.8949444 ,  0.54610626,  0.60006379,  1.07325297,
        0.81503275,  1.02682518,  0.95087436,  0.87739589,  0.62093095,
        0.53067466,  0.5597946 ,  0.66623185,  0.55944734,  0.36391089,
        0.2365026 ,  0.45410366,  0.44427956,  0.24683359,  0.24054826,
        0.28865651,  0.86028882,  0.62632046,  0.50848226,  0.55349611,
        0.76887464,  1.12652291,  0.33799788,  0.41174229,  0.85974504,
        0.60398682,  0.46395588,  0.55812729,  0.74884282,  0.78

In [24]:
np.rint(lr.predict(X_test)).sum()

139.0

In [25]:
np.array(y_test).sum()

144

In [30]:
X_constant = sm.add_constant(X)
mod = sm.OLS(y, X_constant)
res_mult = mod.fit()
print(res_mult.summary())

                            OLS Regression Results                            
Dep. Variable:                  goals   R-squared:                       0.145
Model:                            OLS   Adj. R-squared:                  0.118
Method:                 Least Squares   F-statistic:                     5.404
Date:                Wed, 08 Feb 2023   Prob (F-statistic):           1.31e-23
Time:                        19:33:20   Log-Likelihood:                -1424.9
No. Observations:                1316   AIC:                             2932.
Df Residuals:                    1275   BIC:                             3144.
Df Model:                          40                                         
Covariance Type:            nonrobust                                         
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     0.67

In [76]:
X

date  shots  powerPlayTimeOnIce  penaltyMinutes  shifts  \
2005020004   7323      5               378.0               2      21   
2005020020   7325      1               434.0               0      22   
2005020029   7326      3               450.0               4      21   
2005020042   7328      6               272.0               2      18   
2005020054   7330      6               272.0               0      17   
...           ...    ...                 ...             ...     ...   
2022020566  13617      6                98.0               0      24   
2022020580  13619      5               355.0               2      23   
2022020599  13622      7               120.0               0      25   
2022020617  13624      2                95.0               0      20   
2022020622  13625      4               353.0               0      19   

            timeOnIce  isHome  isOT  Anaheim Ducks  Arizona Coyotes  ...  \
2005020004     1056.0       1     0              0                0  ...   
2005020020     1064.0       1     0              0                0  ...   
2005020029      981.0       0     0              0                0  ...   
2005020042      903.0       1     0              0                0  ...   
2005020054      833.0       0     0              0                0  ...   
...               ...     ...   ...            ...              ...  ...   
2022020566     1277.0       1     1              0                0  ...   
2022020580     1171.0       1     0              0                0  ...   
2022020599     1233.0       1     1              0                0  ...   
2022020617     1088.0       0     0              0                0  ...   
2022020622     1349.0       1     0              0                0  ...   

            Phoenix Coyotes  Pittsburgh Penguins  San Jose Sharks  \
2005020004                0                    0                0   
2005020020                0                    0                0   
2005020029                0                    0                0   
2005020042                0                    0                0   
2005020054                0                    0                0   
...                     ...                  ...              ...   
2022020566                0                    0                0   
2022020580                0                    0                0   
2022020599                0                    0                0   
2022020617                0                    0                0   
2022020622                0                    0                0   

            Seattle Kraken  St. Louis Blues  Tampa Bay Lightning  \
2005020004               0                0                    0   
2005020020               0                0                    0   
2005020029               0                0                    0   
2005020042               0                0                    0   
2005020054               0                0                    0   
...                    ...              ...                  ...   
2022020566               0                0                    0   
2022020580               0                0                    0   
2022020599               0                0                    0   
2022020617               0                0                    0   
2022020622               0                0                    0   

            Toronto Maple Leafs  Vancouver Canucks  Vegas Golden Knights  \
2005020004                    0                  0                     0   
2005020020                    0                  0                     0   
2005020029                    0                  0                     0   
2005020042                    0                  0                     0   
2005020054                    0                  0                     0   
...                         ...                ...                   ...   
2022020566                    0                  0       

In [77]:
y

2005020004    2
2005020020    0
2005020029    0
2005020042    1
2005020054    1
             ..
2022020566    1
2022020580    3
2022020599    2
2022020617    1
2022020622    0
Name: goals, Length: 1316, dtype: int32

In [78]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)  # apply scaling on training data
Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

pipe.score(X_test, y_test)

C:\Users\Anshef\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.5106382978723404

In [79]:
X_train

date  shots  powerPlayTimeOnIce  penaltyMinutes  shifts  \
2016020465  11414      3               178.0               0      24   
2015020576  11064      6               545.0               0      23   
2017020166  11729      5                 0.0               0      21   
2006020133   7708      4               248.0               0      25   
2015020663  11078      4               441.0               0      20   
...           ...    ...                 ...             ...     ...   
2019020154  12455      9               181.0               2      24   
2019020712  12536      4               552.0               0      20   
2022020312  13581      4               307.0               0      24   
2016020348  11398      4               569.0               4      21   
2019020653  12528      3               218.0               0      19   

            timeOnIce  isHome  isOT  Anaheim Ducks  Arizona Coyotes  ...  \
2016020465     1199.0       1     0              0                0  ...   
2015020576     1537.0       0     1              0                0  ...   
2017020166      982.0       0     0              0                0  ...   
2006020133     1033.0       0     0              0                0  ...   
2015020663     1271.0       0     0              0                0  ...   
...               ...     ...   ...            ...              ...  ...   
2019020154     1359.0       0     1              0                0  ...   
2019020712     1299.0       1     0              0                0  ...   
2022020312     1383.0       1     0              0                0  ...   
2016020348     1487.0       1     0              0                0  ...   
2019020653     1060.0       1     0              0                0  ...   

            Phoenix Coyotes  Pittsburgh Penguins  San Jose Sharks  \
2016020465                0                    0                0   
2015020576                0                    0                0   
2017020166                0                    0                0   
2006020133                0                    0                0   
2015020663                0                    0                0   
...                     ...                  ...              ...   
2019020154                0                    0                0   
2019020712                0                    0                0   
2022020312                0                    0                0   
2016020348                0                    0                0   
2019020653                0                    0                1   

            Seattle Kraken  St. Louis Blues  Tampa Bay Lightning  \
2016020465               0                0                    0   
2015020576               0                0                    0   
2017020166               0                0                    0   
2006020133               0                0                    0   
2015020663               0                0                    0   
...                    ...              ...                  ...   
2019020154               0                0                    0   
2019020712               0                0                    0   
2022020312               0                0                    0   
2016020348               0                0                    0   
2019020653               0                0                    0   

            Toronto Maple Leafs  Vancouver Canucks  Vegas Golden Knights  \
2016020465                    0                  0                     0   
2015020576                    0                  0                     0   
2017020166                    0                  0                     0   
2006020133                    0                  0                     0   
2015020663                    0                  0                     0   
...                         ...                ...                   ...   
2019020154                    0                  0       

In [80]:
pipe.predict(X_test)

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 3, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 2, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1,

In [81]:
print(f'{pipe.predict(X_test).sum()} = {y_test.sum()}')

111 = 216


In [38]:
pipe.predict_proba(X_test)

array([[8.10900481e-01, 1.89099519e-01],
       [2.18819480e-03, 9.97811805e-01],
       [2.64721117e-02, 9.73527888e-01],
       [4.43734178e-02, 9.55626582e-01],
       [9.99879807e-01, 1.20193445e-04],
       [3.11626521e-02, 9.68837348e-01],
       [9.72534661e-01, 2.74653388e-02],
       [3.87280569e-01, 6.12719431e-01],
       [8.60287182e-02, 9.13971282e-01],
       [4.70134260e-01, 5.29865740e-01],
       [5.63427112e-01, 4.36572888e-01],
       [9.26960896e-01, 7.30391042e-02],
       [9.08949611e-01, 9.10503890e-02],
       [9.86353281e-01, 1.36467192e-02],
       [9.97624547e-01, 2.37545323e-03],
       [7.61821623e-01, 2.38178377e-01],
       [4.38224319e-02, 9.56177568e-01],
       [9.08688728e-01, 9.13112716e-02],
       [9.78089405e-01, 2.19105947e-02],
       [9.90672587e-01, 9.32741280e-03],
       [9.25586001e-01, 7.44139992e-02],
       [1.75338053e-01, 8.24661947e-01],
       [1.92610866e-02, 9.80738913e-01],
       [1.53055621e-01, 8.46944379e-01],
       [9.893769

In [51]:
pipe[1].coef_

array([[-0.00698306, -1.63925782,  0.11645597,  0.11575482, -0.42286824,
        -0.33524299, -0.25974726, -0.23095649,  0.44946512, -0.18599884,
         2.0187269 ,  0.18600729,  0.08810603,  0.12344562,  0.15063419,
        -1.08809227, -0.10138075, -0.04987034, -0.41465033,  0.11871907]])

In [53]:
pipe[1].intercept_

array([0.28983625])

In [54]:
pipe[1].n_features_in_

20

In [64]:
def regression_results(y_true, y_pred):

    # Regression metrics
    explained_variance=metrics.explained_variance_score(y_true, y_pred)
    mean_absolute_error=metrics.mean_absolute_error(y_true, y_pred) 
    mse=metrics.mean_squared_error(y_true, y_pred) 
    mean_squared_log_error=metrics.mean_squared_log_error(y_true, y_pred)
    median_absolute_error=metrics.median_absolute_error(y_true, y_pred)
    r2=metrics.r2_score(y_true, y_pred)

    print('explained_variance: ', round(explained_variance,4))    
    print('mean_squared_log_error: ', round(mean_squared_log_error,4))
    print('r2: ', round(r2,4))
    print('MAE: ', round(mean_absolute_error,4))
    print('MSE: ', round(mse,4))
    print('RMSE: ', round(np.sqrt(mse),4))

In [63]:
regression_results(y_test, pipe.predict(X_test))

explained_variance:  0.84
mean_squared_log_error:  0.0192
r2:  0.8333
MAE:  0.04
MSE:  0.04
RMSE:  0.2
